<?php
function theme_mc_icon($atts)
{
	extract(shortcode_atts(array(
		"type" => "features",
		"style" => "simple",
		"hexagon_size" => "big",
		"hexagon_style" => "default",
		"icon_feature" => "address",
		"icon_social" => "angies-list",
		"icon_template" => "arrow-circle",
		"url" => "",
		"url_target" => 'new_window',
		"title" => '',
		"class" => '',
		"top_margin" => "none"
	), $atts));
	$output = '';
	if($type=="features" && $style=="hexagon")
		$output .= '<' . ($url!="" ? 'a' : 'span') . ($url!="" ? ' href="' . esc_attr($url) . '"' . ($url_target=="new_window" ? ' target="_blank"' : '') : '') . ' class="icon-single hexagon' . ($hexagon_size=="small" ? ' small' : '') . ($hexagon_style=="light" ? ' style-light' : '') . ($class!="" ? ' ' . esc_attr($class) : '') . ($top_margin!="none" ? ' ' . esc_attr($top_margin) : '') . '"' . ($title!="" ? ' title="' . esc_attr($title) . '"' : '') . '>';
	$output .= '<' . ($url!="" && ($type!="features" || ($type=="features" && $style!="hexagon")) ? 'a' : 'span') . ($url!="" && ($type!="features" || ($type=="features" && $style!="hexagon")) ? ' href="' . esc_attr($url) . '"' . ($url_target=="new_window" && ($type!="features" || ($type=="features" && $style!="hexagon")) ? ' target="_blank"' : '') : '') . ' class="' . ($type!="features" || ($type=="features" && $style!="hexagon") ? 'icon-single mc-icon ' : '') . esc_attr($type) . '-' . ($type=="features" ? esc_attr($icon_feature) : ($type=="social" ? esc_attr($icon_social) : esc_attr($icon_template))) . ($class!="" && ($type!="features" || ($type=="features" && $style!="hexagon")) ? ' ' . esc_attr($class) : '') . ($top_margin!="none" && ($type!="features" || ($type=="features" && $style!="hexagon")) ? ' ' . esc_attr($top_margin) : '') . '"' . ($title!="" && ($type!="features" || ($type=="features" && $style!="hexagon")) ? ' title="' . esc_attr($title) . '"' : '') . '></' . ($url!="" && ($type!="features" || ($type=="features" && $style!="hexagon")) ? 'a' : 'span') . '>';
	if($type=="features" && $style=="hexagon")
		$output .= '</' . ($url!="" ? 'a' : 'span') . '>';
	return $output;
}
add_shortcode("mc_icon", "theme_mc_icon");
//visual composer
$icons_features = array(
	"address",
	"ambulance",
	"app",
	"baby",
	"baby-bed",
	"baby-bottle",
	"bacteria",
	"balance",
	"battery",
	"book",
	"box",
	"brain",
	"briefcase",
	"burns",
	"cart",
	"cat",
	"certificate",
	"chart",
	"chat",
	"clock",
	"config",
	"credit-card",
	"cross",
	"dental-shield",
	"dentist",
	"diary",
	"dna",
	"doctor",
	"document",
	"document-missing",
	"dog",
	"drip",
	"ear",
	"email",
	"eye",
	"facebook",
	"first-aid",
	"fitness",
	"frostbite",
	"gallery",
	"glasses",
	"graph",
	"healthcare",
	"heart",
	"heart-beat",
	"home",
	"hospital",
	"id",
	"image",
	"keyboard",
	"lab",
	"laptop",
	"leaf",
	"lifeline",
	"list",
	"location",
	"lock",
	"map",
	"medical-bed",
	"medical-cast",
	"medical-cross",
	"medical-document",
	"medical-results",
	"medical-scissors",
	"medical-staff",
	"minus",
	"mobile",
	"molecule",
	"money",
	"mortar",
	"movie",
	"network",
	"paypal",
	"pen",
	"people",
	"pet-box",
	"phone",
	"piano",
	"pill",
	"pin",
	"plaster",
	"plus",
	"printer",
	"pulse",
	"quote",
	"science",
	"screen",
	"signpost",
	"spa",
	"spa-bamboo",
	"spa-lotion",
	"speaker",
	"stethoscope",
	"syringe",
	"tablet",
	"tags",
	"teddy-bear",
	"test-tube",
	"tick",
	"time",
	"toothbrush",
	"twitter",
	"video",
	"wallet",
	"x-ray"
);
$icons_social = array(
	"angies-list",
	"behance",
	"deviantart",
	"dribbble",
	"email",
	"envato",
	"facebook",
	"flickr",
	"foursquare",
	"github",
	"google-plus",
	"houzz",
	"instagram",
	"linkedin",
	"location",
	"mobile",
	"paypal",
	"pinterest",
	"reddit",
	"rss",
	"skype",
	"soundcloud",
	"spotify",
	"stumbleupon",
	"tumblr",
	"twitter",
	"vimeo",
	"vine",
	"vk",
	"weibo",
	"xing",
	"yelp",
	"youtube"
);
$icons_template = array(
	"arrow-circle",
	"arrow-horizontal-1",
	"arrow-horizontal-2",
	"arrow-horizontal-3",
	"arrow-horizontal-4",
	"arrow-horizontal-5",
	"arrow-vertical-1",
	"arrow-vertical-3",
	"arrow-vertical-4",
	"arrow-vertical-5",
	"cart",
	"check",
	"chevron",
	"comment-1",
	"comment-2",
	"location",
	"mail",
	"menu-1",
	"menu-2",
	"minus-1",
	"minus-2",
	"phone",
	"plus-1",
	"plus-2",
	"remove-1",
	"remove-2",
	"search",
	"quote"
);

vc_map( array(
	"name" => __("Icon", 'medicenter'),
	"base" => "mc_icon",
	"class" => "",
	"controls" => "full",
	"show_settings_on_create" => true,
	"icon" => "icon-wpb-layer-icon",
	"category" => __('MediCenter', 'medicenter'),
	"params" => array(
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Type", 'medicenter'),
			"param_name" => "type",
			"value" => array(__("Feature", 'medicenter') => "features", __("Social", 'medicenter') => "social", __("Template", 'medicenter') => "template")
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Style", 'medicenter'),
			"param_name" => "style",
			"value" => array(__("Simple", 'medicenter') => "simple", __("Hexagon", 'medicenter') => "hexagon"),
			"dependency" => Array('element' => "type", 'value' => 'features')
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Hexagon size", 'medicenter'),
			"param_name" => "hexagon_size",
			"value" => array(__("Big", 'medicenter') => "big", __("Small", 'medicenter') => "small"),
			"dependency" => Array('element' => "style", 'value' => 'hexagon')
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Hexagon style", 'medicenter'),
			"param_name" => "hexagon_style",
			"value" => array(__("Default", 'medicenter') => "default", __("Light", 'medicenter') => "light"),
			"dependency" => Array('element' => "style", 'value' => 'hexagon')
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Icon", 'medicenter'),
			"param_name" => "icon_feature",
			"value" => $icons_features,
			"dependency" => Array('element' => "type", 'value' => array('features'))
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Icon", 'medicenter'),
			"param_name" => "icon_social",
			"value" => $icons_social,
			"dependency" => Array('element' => "type", 'value' => array('social'))
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Icon", 'medicenter'),
			"param_name" => "icon_template",
			"value" => $icons_template,
			"dependency" => Array('element' => "type", 'value' => array('template'))
		),
		array(
			"type" => "textfield",
			"class" => "",
			"heading" => __("Url", 'medicenter'),
			"param_name" => "url",
			"value" => ""
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Url target", 'medicenter'),
			"param_name" => "url_target",
			"value" => array(
				__("new window", 'medicenter') => 'new_window', 
				__("same window", 'medicenter') => 'same_window'
			)
		),
		array(
			"type" => "textfield",
			"class" => "",
			"heading" => __("Title", 'medicenter'),
			"param_name" => "title",
			"value" => ""
		),
		array(
			"type" => "textfield",
			"holder" => "div",
			"class" => "",
			"heading" => __("Extra class name", 'medicenter'),
			"param_name" => "class",
			"value" => ""
		),
		array(
			"type" => "dropdown",
			"class" => "",
			"heading" => __("Top margin", 'medicenter'),
			"param_name" => "top_margin",
			"value" => array(__("None", 'medicenter') => "none", __("Page (small)", 'medicenter') => "page-margin-top", __("Section (large)", 'medicenter') => "page-margin-top-section")
		)
	)
));
?>
